apiVersion: apps/v1
kind: Deployment
metadata:
  name: abiotic-factor-server
  namespace: abiotic-factor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: abiotic-factor-server
  template:
    metadata:
      labels:
        app: abiotic-factor-server
    spec:
      # hostNetwork: pod usa a rede do i9 diretamente. Resolve jogar no mesmo host (EOS).
      # Servidor escuta direto em 7777/UDP e 27015/UDP no IP do i9.
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: abiotic-factor-server
          image: andrewsav/abiotic-factor:latest
          ports:
            - containerPort: 7777
              hostPort: 7777
              protocol: UDP
            - containerPort: 27015
              hostPort: 27015
              protocol: UDP
          env:
            - name: args
              value: >-
                -userdir=/server/AbioticFactor/Saved
                -newconsole
                -useperfthreads
                -NoAsyncLoadingThread
                -UseMultithreadForDS
                -MaxServerPlayers=6
                -PORT=7777
                -QUERYPORT=27015
                -ServerName=Servidor-do-Andre-Abiotic
                -SaveName=Mundo
                -SteamServerName=Servidor-do-Andre-Abiotic
          resources:
            requests:
              memory: "6Gi"
              cpu: "2000m"
            limits:
              memory: "12Gi"
              cpu: "6000m"
          volumeMounts:
            - name: abiotic-factor-data
              mountPath: /server
      volumes:
        - name: abiotic-factor-data
          persistentVolumeClaim:
            claimName: abiotic-factor-pvc
