apiVersion: apps/v1
kind: Deployment
metadata:
  name: abiotic-factor-server
  namespace: abiotic-factor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: abiotic-factor-server
  template:
    metadata:
      labels:
        app: abiotic-factor-server
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "abiotic-factor"
        vault.hashicorp.com/agent-inject-secret-server-password: "wol/data/abiotic-factor"
        vault.hashicorp.com/agent-inject-template-server-password: |
          {{- with secret "wol/data/abiotic-factor" -}}
          {{ index .Data.data "server-password" }}
          {{- end -}}
        vault.hashicorp.com/agent-pre-populate-only: "true"
    spec:
      serviceAccountName: abiotic-factor-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: abiotic-factor-server
          image: andrewsav/abiotic-factor:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              SENHA="$(cat /vault/secrets/server-password)"
              export args="-userdir=/server/AbioticFactor/Saved -newconsole -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -MaxServerPlayers=6 -PORT=7777 -QUERYPORT=27015 -ServerName=Servidor-do-Andre-Abiotic -SaveName=Mundo -SteamServerName=Servidor-do-Andre-Abiotic -ServerPassword=${SENHA}"
              exec /entrypoint.sh
          ports:
            - containerPort: 7777
              hostPort: 7777
              protocol: UDP
            - containerPort: 27015
              hostPort: 27015
              protocol: UDP
          resources:
            requests:
              memory: "6Gi"
              cpu: "2000m"
            limits:
              memory: "12Gi"
              cpu: "6000m"
          volumeMounts:
            - name: abiotic-factor-data
              mountPath: /server
      volumes:
        - name: abiotic-factor-data
          persistentVolumeClaim:
            claimName: abiotic-factor-pvc
