apiVersion: v1
kind: PersistentVolume
metadata:
  name: abiotic-factor-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/rancher/abiotic-factor
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - andre-reis-hm570
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abiotic-factor-pvc
  namespace: abiotic-factor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 25Gi
