apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    managed-by: argocd    # adiciona essa linha
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/rancher/vault
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - andre-reis-hm570
